FROM centos
RUN yum install -y git
RUN cd ~ && git clone https://github.com/csong27/ml-model-remember.git
RUN cd ~ && curl https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso > boot2docker.iso
